### ISSUE TITLE
cannot find package "github.com/btcsuite/btcd/btcec"

### ISSUE THREAD

**Issue by TT1943** [blockcypher/btcutils#3]
When I run `go build`, I have the following issue.
signer.go:9:2: cannot find package "github.com/btcsuite/btcd/btcec" in any of:
	/usr/local/go/src/github.com/btcsuite/btcd/btcec (from $GOROOT)
	($GOPATH not set)

Looks like github.com/btcsuite/btcd/btcec is no longer existed

**Comment by acityinohio** [comment]
Sorry for the trouble! Realized that we missed a step in the readme for folks who don't have the btcd/btcec library installed. You have to `go get` the remote repo to install the package library before you can have a successful build; aka, run this code before building:

```shell
go get github.com/btcsuite/btcd/btcec
```

Go get will download the repo from github and install remotely. You can read more about how it works [here](https://golang.org/doc/code.html#remote)

I'm going to update the readme with proper instructions, thanks for helping us catch the missing piece!

**Comment by Fooooooooooox** [comment]
☻

**Comment by SantiiRepair** [comment]
@acityinohio dude `github.com/btcsuite/btcd/btcec` was deleted

**Comment by quentinlesceller** [comment]
Looks unrelated to this package?

**Comment by SantiiRepair** [comment]
@quentinlesceller The question was related but didn't know this package was moved to another repository, my bad
